export interface TipoResponse {
  idTipo: number;
  nmCategoria: CategoriaEnum;
  cdTipo: string;
  dsTipo: string;
  flAtivo: StatusAtivo;
}

export enum CategoriaEnum {
  FLUXO = 'FLUXO',
  AREA = 'AREA',
  OBRIG_CLASSIFICACAO = 'OBRIG_CLASSIFICACAO',
  OBRIG_PERIODICIDADE = 'OBRIG_PERIODICIDADE',
  OBRIG_CRITICIDADE = 'OBRIG_CRITICIDADE',
  OBRIG_NATUREZA = 'OBRIG_NATUREZA',
  CLASSIFICACAO_STATUS_SOLICITACAO = 'CLASSIFICACAO_STATUS_SOLICITACAO'
}

export enum StatusAtivo {
  S = 'S',
  N = 'N'
}

export enum TipoEnum {
    // FLUXO
    CORRESPONDENCIA = 'CORRESPONDENCIA',
    OBRIGACAO = 'OBRIGACAO',
    
    // AREA
    ATRIBUIDA = 'ATRIBUIDA',
    CONDICIONANTE = 'CONDICIONANTE',
    
    // CLASSIFICACAO OBRIG
    PRINCIPAL = 'PRINCIPAL',
    CONDICIONADA = 'CONDICIONADA',
    SUPERVINIENTE = 'SUPERVINIENTE',
    
    // PERIODICIDADE OBRIG
    SEMANAL = 'SEMANAL',
    MENSAL = 'MENSAL',
    ANUAL = 'ANUAL',
    SEMESTRAL = 'SEMESTRAL',
    BIMESTRAL = 'BIMESTRAL',
    TRIMESTRAL = 'TRIMESTRAL',
    UNICA = 'UNICA',
    EXTRAORDINARIA = 'EXTRAORDINARIA',
    
    // CRITICIDADE OBRIG
    ALTA = 'ALTA',
    MEDIA = 'MEDIA',
    BAIXA = 'BAIXA',
    
    // NATUREZA OBRIG
    CONTRATUAL = 'CONTRATUAL',
    REGULATORIA = 'REGULATORIA',
    AMBIENTAL = 'AMBIENTAL',
    ECONOMICO_FINANCEIRA = 'ECONOMICO_FINANCEIRA',
    JURIDICA_ADMINISTRATIVA = 'JURIDICA_ADMINISTRATIVA',
    TECNICA_OPERACIONAL = 'TECNICA_OPERACIONAL',
      
    // CLASSIFICACAO STATUS SOLICITACAO
    TODOS = 'TODOS',
}
