name: Deploy for Way Web DEV

on:
  push:
    branches: [ develop ]


jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      WEBHOOK_URL: "https://chat.googleapis.com/v1/spaces/AAQA5qsWFdQ/messages?key=AIzaSyDdI0hCZtE6vySjMm-WEfRq3CPzqKqqsHI&token=VyWYfeqljUfRTIYU-mvpjOntN4ykR2me8p6Cn_ROEPg"
      GIT_BRANCH: "develop"

    steps:
      - name: Checkout código
        uses: actions/checkout@v3

      - name: Configurar Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Cache Docker layers
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Testar build da imagem Docker
        id: docker-build
        uses: docker/build-push-action@v4
        with:
          context: .
          push: false
          tags: way-web:latest
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache-new,mode=max

      - name: Move cache
        run: |
          rm -rf /tmp/.buildx-cache
          mv /tmp/.buildx-cache-new /tmp/.buildx-cache

      - name: Cache APT packages
        uses: awalsh128/cache-apt-pkgs-action@latest
        with:
          packages: openfortivpn
          version: 1.0

      - name: Conectar VPN
        env:
          VPN_SERVER: vpn1.way262.com.br
          VPN_USER: T_carlos.silva
          VPN_PASS: Twaybrasil@262
          VPN_CERT: cb80f98b2d89f9beb935c8c42b8854ab3b456050a82aaa2a7cafee156b133f7e
        run: |
          # Iniciar conexão VPN em background
          sudo openfortivpn $VPN_SERVER \
            --username="$VPN_USER" \
            --password="$VPN_PASS" \
            --trusted-cert="$VPN_CERT" > vpn.log 2>&1 &
          
          # Aguardar conexão VPN com timeout inteligente
          echo "Aguardando conexão VPN..."
          for i in {1..30}; do
            if ping -c 1 -W 2 10.132.4.128 >/dev/null 2>&1; then
              echo "VPN conectada em ${i} segundos"
              break
            fi
            if [ $i -eq 30 ]; then
              echo "Timeout: VPN não conectou em 30 segundos"
              cat vpn.log
              exit 1
            fi
            sleep 1
          done

      - name: Deploy aplicação
        env:
          COMMIT_MESSAGE: ${{ github.event.head_commit.message }}
        run: |
          sshpass -p "Suporte@#0608" ssh -o StrictHostKeyChecking=no rtech@10.132.4.129 \
          "cd /home/rtech/way-correspondencias-web && ./deploy.sh \"${COMMIT_MESSAGE//$'\n'/ }\""

      - name: Send failure message to Google Chat
        if: failure()
        env:
          COMMIT_MESSAGE: ${{ github.event.head_commit.message }}
        run: |
          # Preparar payload no formato do webhook
          PAYLOAD=$(cat << EOF
          {
            "text": "Deploy do projeto Way",
            "cards": [
              {
                "sections": [
                  {
                    "widgets": [
                      {
                        "keyValue": {
                          "topLabel": "Projeto",
                          "content": "way-correspondencias-web"
                        }
                      },
                      {
                        "keyValue": {
                          "topLabel": "Branch",
                          "content": "$GIT_BRANCH"
                        }
                      },
                      {
                        "keyValue": {
                          "topLabel": "Status",
                          "content": "FAILED"
                        }
                      },
                      {
                        "keyValue": {
                          "topLabel": "Mensagem",
                          "content": "Deploy falhou na Pipeline CI/CD"
                        }
                      },
                      {
                        "keyValue": {
                          "topLabel": "Commit",
                          "content": "$COMMIT_MESSAGE"
                        }
                      }
                    ]
                  }
                ]
              }
            ]
          }
          EOF
          )
          
          # Enviar webhook
          curl -s -X POST -H "Content-Type: application/json" -d "$PAYLOAD" "$WEBHOOK_URL"
